### ISSUE TITLE
double github link

### ISSUE THREAD

**Issue by genseirin** [alexandruradovici/profiles#1]
The code
`{{github.link:https://github.com/organizations/xyz| }}`
created a double link
`href="https://github.com/organizations/xyzhttps://github.com/organizations/xyz"`.

The problem seems to be in syntax.php where `$ahref = $ahref.$parameter;` is processed even if `$type == "link"`. Changing line 66 `if ($service=="facebook")` to `elseif ($service=="facebook")` seems to fix it.

**Comment by alexandruradovici** [comment]
Thank you, fixed,
